title: Karen Gask
description: >- # this means to ignore newlines until "baseurl:"
  Data scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gaskyk
github_username:  gaskyk

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.14.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# For posts
paginate: 10 
paginate_path: /recent/page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      excerpt: ""
      author_profile: true
      read_time: true

# For pages
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Add author
author:
  name: "Karen Gask"
  #avatar: "/assets/images/bio-photo.jpg"
  bio: "Data scientist"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gaskyk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gaskyk"
