title: Karen Gask
description: >- # this means to ignore newlines until "baseurl:"
  Data scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gaskyk
github_username:  gaskyk

# Build settings
markdown: kramdown
#remote_theme: "mmistakes/minimal-mistakes@4.14.1"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

# For posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
